# Generated by Django 3.2.12 on 2022-02-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamain',
            name='checkedImage',
            field=models.ImageField(default='default', upload_to='images/'),
            preserve_default=False,
        ),
    ]
